# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pocketci < Formula
  desc "Local-first CI/CD runtime with JavaScript/TypeScript pipelines"
  homepage "https://github.com/jtarchie/pocketci"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.5/pocketci_0.1.5_darwin_amd64.tar.gz"
      sha256 "8e43ad881ffec41b61074cbe2bb7449810d055559b6173166dcb9331551d4d37"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.5/pocketci_0.1.5_darwin_arm64.tar.gz"
      sha256 "f2154a444fe820310b447cb8a2e2b80192cde3d0ddd80f09386b8b475bd0a0af"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.5/pocketci_0.1.5_linux_amd64.tar.gz"
      sha256 "ea4e2239f935b7478940d865f5d13280a0d972223be910ae2982a549b136fe1f"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.5/pocketci_0.1.5_linux_arm64.tar.gz"
      sha256 "f1e63eff01c34f713d110e90c589ce83449b378127f801646bcee0a5ef735e9e"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  test do
    system "#{bin}/pocketci", "--version"
  end
end
