# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pocketci < Formula
  desc "Local-first CI/CD runtime with JavaScript/TypeScript pipelines"
  homepage "https://github.com/jtarchie/pocketci"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.4/pocketci_0.1.4_darwin_amd64.tar.gz"
      sha256 "dc5dee9a54ccdd173ac93647e94d71bb039f20b337631b7e294db816986d0838"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.4/pocketci_0.1.4_darwin_arm64.tar.gz"
      sha256 "00f750c4dd16e9d721fdf7cb19068d129b9f782733abd22c4aa64de08e5dc175"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.4/pocketci_0.1.4_linux_amd64.tar.gz"
      sha256 "cfb7fddfa96f71be520565709a3952205035345a761d35e6b6553b890af84116"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.4/pocketci_0.1.4_linux_arm64.tar.gz"
      sha256 "3eec9f81819fc52bf05d0b6801194b944f76d4c7298246fd857e511c351571e9"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  test do
    system "#{bin}/pocketci", "--version"
  end
end
