# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pocketci < Formula
  desc "Local-first CI/CD runtime with JavaScript/TypeScript pipelines"
  homepage "https://github.com/jtarchie/pocketci"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.3/pocketci_0.1.3_darwin_amd64.tar.gz"
      sha256 "e59661492a30f79107ee122f55d77445e0a9f3218b0505f8c15736dca31e21fd"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.3/pocketci_0.1.3_darwin_arm64.tar.gz"
      sha256 "96d181e7b8ffa64dce24e8eb8956abba6f4a7201782e99a41a1e23e17e42cd08"

      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.3/pocketci_0.1.3_linux_amd64.tar.gz"
      sha256 "a052f9a1611f614302292e6f02157d147ba98a1c169eb270542466ab74b65eb9"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/pocketci/releases/download/v0.1.3/pocketci_0.1.3_linux_arm64.tar.gz"
      sha256 "7514420d6214acd17ce7a3f69ee7321834304942720fec1fd5b2bffd965b5a89"
      define_method(:install) do
        bin.install "pocketci"
      end
    end
  end

  test do
    system "#{bin}/pocketci", "--version"
  end
end
