assert:
  execution:
    - "success-job"

jobs:
  - name: success-job
    plan:
      - task: do-entry
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo do-entry"]
        assert:
          code: 0
          stdout: "do-entry"
      - do:
          - task: do-task
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: busybox
              run:
                path: sh
                args: ["-c", "exit 0"]
            assert:
              code: 0
        ensure:
          task: ensure-task
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: busybox
            run:
              path: sh
              args: ["-c", "exit 11"]
          assert:
            code: 11
    assert:
      execution:
        - "do-entry"
        - "do-task"
        - "ensure-task"
