assert:
  execution:
    - "image-shorthand-job"

jobs:
  - name: image-shorthand-job
    plan:
      - task: image-shorthand-task
        config:
          platform: linux
          image: busybox
          run:
            path: sh
            args: ["-c", "exit 0"]
        assert:
          code: 0
