assert:
  execution:
    - "error-job"

jobs:
  - name: error-job
    plan:
      - task: error-entry
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo error-entry"]
        assert:
          code: 0
          stdout: "error-entry"
      - task: erroring-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: this-doesnt-exist-please-no-image
          run:
            path: this-doesnt-exist-please-no-image
        on_error:
          task: on-erroring-task
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: busybox
            run:
              path: sh
              args: ["-c", "echo 'on-erroring-task'"]
          assert:
            stdout: "on-erroring-task"
            code: 0
    assert:
      execution:
        - "error-entry"
        - "erroring-task"
        - "on-erroring-task"
