assert:
  execution:
    - "failing-job"

jobs:
  - name: failing-job
    plan:
      - task: failing-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo failing && exit 1"]
        assert:
          code: 1
      - task: skipped-task-a
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo should-not-run"]
      - task: skipped-task-b
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo should-not-run"]
    assert:
      execution:
        - "failing-task"
