assert:
  execution:
    - "success-job"

jobs:
  - name: success-job
    plan:
      - task: try-entry
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args: ["-c", "echo try-entry"]
        assert:
          code: 0
          stdout: "try-entry"
      - try:
          - task: try-task
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: busybox
              run:
                path: sh
                args: ["-c", "exit 1"]
            assert:
              code: 1
    assert:
      execution:
        - "try-entry"
        - "try-task"
