assert:
  execution:
    - "stderr-job"

jobs:
  - name: stderr-job
    plan:
      - task: stderr-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args:
              - "-c"
              - |
                  echo "this goes to stdout"
                  echo "this goes to stderr" >&2
        assert:
          code: 0
          stdout: "this goes to stdout"
          stderr: "this goes to stderr"
