import { defineConfig } from "vitepress";

export default defineConfig({
  title: "PocketCI",
  description: "Local-first PocketCI runtime documentation",
  base: "/docs/",
  cleanUrls: false,
  deadLinks: "error",
  themeConfig: {
    nav: [
      { text: "Guides", link: "/guides/" },
      { text: "Runtime API", link: "/runtime/" },
      { text: "Operations", link: "/operations/" },
      { text: "Drivers", link: "/drivers/" },
    ],
    sidebar: {
      "/runtime/": [
        { text: "Overview", link: "/runtime/" },
        { text: "runtime.run()", link: "/runtime/runtime-run" },
        { text: "agent.run()", link: "/runtime/runtime-agent" },
        { text: "Volumes", link: "/runtime/volumes" },
        { text: "notify", link: "/runtime/notify" },
      ],
      "/guides/": [
        { text: "Overview", link: "/guides/" },
        { text: "Getting Started", link: "/guides/getting-started" },
        { text: "Production Setup", link: "/guides/production" },
        { text: "Run Pipelines", link: "/guides/run" },
        { text: "Webhooks", link: "/guides/webhooks" },
        { text: "Scheduling", link: "/guides/scheduling" },
        { text: "MCP", link: "/guides/mcp" },
        { text: "YAML Pipelines", link: "/guides/yaml-pipelines" },
      ],
      "/operations/": [
        { text: "Overview", link: "/operations/" },
        { text: "Authentication", link: "/operations/authentication" },
        { text: "Authorization (RBAC)", link: "/operations/rbac" },
        { text: "Storage", link: "/operations/storage" },
        { text: "Secrets", link: "/operations/secrets" },
        { text: "Caching", link: "/operations/caching" },
        { text: "Execution Queue", link: "/operations/execution-queue" },
        { text: "Feature Gates", link: "/operations/feature-gates" },
      ],
      "/cli/": [
        { text: "Overview", link: "/cli/" },
        { text: "Runner", link: "/cli/runner" },
        { text: "Server", link: "/cli/server" },
        { text: "Login", link: "/cli/login" },
        { text: "Pipeline Set", link: "/cli/pipeline-set" },
        { text: "Pipeline Run", link: "/cli/pipeline-run" },
        { text: "Pipeline Trigger", link: "/cli/pipeline-trigger" },
        { text: "Pipeline Rm", link: "/cli/pipeline-rm" },
        { text: "Pipeline Ls", link: "/cli/pipeline-ls" },
        { text: "Pipeline Pause", link: "/cli/pipeline-pause" },
        { text: "Pipeline Unpause", link: "/cli/pipeline-unpause" },
        { text: "Pipeline Schedule", link: "/cli/schedule" },
      ],
      "/api/": [
        { text: "Overview", link: "/api/" },
        { text: "Pipelines", link: "/api/pipelines" },
        { text: "Runs", link: "/api/runs" },
        { text: "Webhooks", link: "/api/webhooks" },
        { text: "Schedules", link: "/api/schedules" },
        { text: "Drivers", link: "/api/drivers" },
        { text: "Features", link: "/api/features" },
        { text: "MCP", link: "/api/mcp" },
      ],
      "/drivers/": [
        { text: "Overview", link: "/drivers/" },
        { text: "Native Resources", link: "/drivers/native-resources" },
        { text: "Implementing Drivers", link: "/drivers/implementing-driver" },
      ],
    },
    socialLinks: [
      { icon: "github", link: "https://github.com/jtarchie/pocketci" },
    ],
  },
});
